apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcpg-cp.fullname" . }}
  labels:
    {{- include "mcpg-cp.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.targetPort }}
      protocol: TCP
    - name: grpc
      port: {{ .Values.service.grpc.port }}
      targetPort: {{ .Values.service.grpc.targetPort }}
      protocol: TCP
      appProtocol: grpc
  selector:
    {{- include "mcpg-cp.selectorLabels" . | nindent 4 }}
